// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuH7YXo7zNKe-nJJotlSkH_2PuLrd2j_A',
    appId: '1:48256565639:android:46189816a20f5dccead322',
    messagingSenderId: '48256565639',
    projectId: 'notesapplication-29bbc',
    storageBucket: 'notesapplication-29bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKYO-19TsFAuLAw_BZ9a0W9uCEz0YWxo',
    appId: '1:48256565639:ios:01fac0d0e8745675ead322',
    messagingSenderId: '48256565639',
    projectId: 'notesapplication-29bbc',
    storageBucket: 'notesapplication-29bbc.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDKYO-19TsFAuLAw_BZ9a0W9uCEz0YWxo',
    appId: '1:48256565639:ios:01fac0d0e8745675ead322',
    messagingSenderId: '48256565639',
    projectId: 'notesapplication-29bbc',
    storageBucket: 'notesapplication-29bbc.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );
}
